### ISSUE TITLE
socks-hub转发overtls 客户端的时候 加入用户名和密码使用 socks-hub报错

### ISSUE THREAD

**Issue by happytrudy** [ssrlive/socks-hub#3]
overtls做客户端 config配置文件如下 关键信息隐藏了
   {
        "remarks": "jaSV",
        "method": "none",
        "password": "password",
        "tunnel_path": "/user/",
        "client_settings": {
            "server_host": "**********",
            "server_port": 443,
            "server_domain": "*****************",
            “listen_user”: "admin",
            "listen_password":  "admin",
            "listen_host": "127.0.0.1",
            "listen_port": 1080
        }
    }
启动socks-hub命令如下
socks-hub -l 0.0.0.0:8118 -s 127.0.0.1:1080 -u admin -p admin -v debug

启动之后通过设置http代理 8118端口访问网站， socks-hub报错如下
![image](https://github.com/ssrlive/socks-hub/assets/61214170/464f7c9d-01c3-41c8-abf5-1d9f894b7fe1)
浏览器网页打不开
去掉上面的overtls监听用户名和密码配置之后，修改socks-hub启动命令去掉用户名和密码参数 再次启动代理， 浏览器一切正常可以访问

**Comment by happytrudy** [comment]
请问是因为命令socks-hub的命令写错了吗?
socks-hub -l 0.0.0.0:8118 -s 127.0.0.1:1080 -u "admin" -p "admin" -v debug 这貌似没区别
我浏览器使用SwitchyOmega密码也设置了 但是确实不行 检查了好几遍设置

**Comment by ssrlive** [comment]
浏览器 -> socks-hub -> overtls

前者支持密码, 后者目前不支持.

一堆密码会把人搞疯掉的.

**Comment by happytrudy** [comment]
socks-hub的 -u 和-p参数 是针对需要代理的socks5代理的用户名和密码 
还是socks-hub 做http代理认证的用户名和密码?
是有点绕 从你的readme看貌似是第一种 针对需要代理的socks5代理的用户名和密码 也就是socks-hub代理之后无认证

**Comment by ssrlive** [comment]
![image](https://github.com/ssrlive/socks-hub/assets/30760636/5334ff00-62cc-4711-8a24-eb4eef9062a6)

**Comment by ssrlive** [comment]
`Client authentication username` 为了避免产生歧义, 特别写是 client , 不是 server, 看来没戏, 不如一直啥密码也不支持.

**Comment by happytrudy** [comment]
> `Client authentication username` 为了避免产生歧义, 特别写是 client , 不是 server, 看来没戏, 不如一直啥密码也不支持.

看来我理解反了额

**Comment by ssrlive** [comment]
如果加入两组密码, 可能对用户更是一个大坑.

**Comment by happytrudy** [comment]
主要是overtls那边有密码 这两个连着用 相当于断了额 所以一般人认为是第一种情况 也可能没人这样用 我期待你加入分流规则的文件支持

**Comment by ssrlive** [comment]
把那边的密码去掉.

**Comment by happytrudy** [comment]
我知道怎么改了

**Comment by chenxudong2020** [comment]
很奇怪 还是报密码错误 
![image](https://github.com/ssrlive/socks-hub/assets/61214170/9b658c51-f51e-4f38-b7e3-3c2fcdab6008)
![image](https://github.com/ssrlive/socks-hub/assets/61214170/334da2de-d071-4860-bda8-d56005f0ecb2)

**Comment by ssrlive** [comment]
对于 http 代理来说, http 密码就是个骗鬼的玩意儿.看看.

![image](https://github.com/ssrlive/socks-hub/assets/30760636/1ee4941c-9c8d-4fc3-be50-7106ebfd0f53)

**Comment by happytrudy** [comment]
> 对于 http 代理来说, http 密码就是个骗鬼的玩意儿.看看.
> 
> ![image](https://private-user-images.githubusercontent.com/30760636/308821930-1ee4941c-9c8d-4fc3-be50-7106ebfd0f53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxODk3NDEsIm5iZiI6MTcwOTE4OTQ0MSwicGF0aCI6Ii8zMDc2MDYzNi8zMDg4MjE5MzAtMWVlNDk0MWMtOWM4ZC00ZmMzLWJlNTAtNzEwNmViZmQwZjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA2NTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzOTNkMGVkMjZmNzFiZWZjNWJhYmY2OGRlOGU2M2EwMTRhYjczNWM0M2Q0OWU4YTdhNmIxOGVmNTQyYTgwMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j8L-R9UZGHflfNQz2kb8mBc-ziBm8RtdGGoOjS-bXEI)

就是骗小白的 只是我测试下 发现插件输入用户名和密码是正确的 但是后台日志打印还是fail

**Comment by ssrlive** [comment]
现在还没搞明白从 浏览器传出来的 带 密码 的 http 代理是个啥数据格式.

**Comment by ssrlive** [comment]
好了.

**Comment by happytrudy** [comment]
> 好了.

改的好快 马上测试， 本来我在想这个组件只是在ssr客户端内部调用 我这样用的无非是想把socks5代理成http 其实我想到v2ray本来可以支持soks5出站同时可以进行分流 所以想着用v2ray在充当这个角色 如果这个组件能支持规则分流其实规则可以利用v2ray等类似软件的规则就更加好了 这样所有的客户端可以都支持规则分流了

**Comment by ssrlive** [comment]
哪个提供一个规则库?否则这针线活不是人干的.

**Comment by chenxudong2020** [comment]
> 哪个提供一个规则库?否则这针线活不是人干的.

![image](https://github.com/ssrlive/socks-hub/assets/61214170/80e46cd1-2378-4de4-89c3-1e86127b392e)
![image](https://github.com/ssrlive/socks-hub/assets/61214170/99385529-95f3-4569-808e-0bde2b9b921a)
v2ray里面有这样的文件 v2raya和hiddify next内部也有

**Comment by ssrlive** [comment]
你学 rust 吧, 写一个规则库. 真的厌倦这没完没了的重复造轮子.

**Comment by chenxudong2020** [comment]
> 你学 rust 吧, 写一个规则库. 真的厌倦这没完没了的重复造轮子.
没让你写规则库，只是利用现有的库，还有我把你这边的软件做成群晖套件了 可以玩下
https://github.com/chenxudong2020/docker_build_action/releases/tag/v1.0.0
测试了你刚刚的修改发现 现在用Proxy SwitchyOmega 这个软件 设置任何用户名和密码都可以打开目标网站
查看日志确实打印了faild但是后面又可以正常输出日志
![image](https://github.com/ssrlive/socks-hub/assets/61214170/cd59fe11-3082-4af4-b540-36ff8644c59b)

**Comment by ssrlive** [comment]
改了.
![image](https://github.com/ssrlive/socks-hub/assets/30760636/000473b3-4013-4045-86a7-a9c0493a9862)

**Comment by happytrudy** [comment]
> 改了. ![image](https://private-user-images.githubusercontent.com/30760636/308856904-000473b3-4013-4045-86a7-a9c0493a9862.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxOTY5NDIsIm5iZiI6MTcwOTE5NjY0MiwicGF0aCI6Ii8zMDc2MDYzNi8zMDg4NTY5MDQtMDAwNDczYjMtNDAxMy00MDQ1LTg2YTctYTljMDQ5M2E5ODYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA4NTA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMWJhNWZiZmVlMmViNDgxODQ0NTMyNWQ5MDBkMWVhMzM2NDJhNTAwYjgwYTM5MjZkNTBjMjhhNjQ2YTUyMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jJJgEReqBEZ-u7SEdMRixVA8NK4zB14sVdJVCDA8u1M)

重新发版本吧 我再次打包

**Comment by ssrlive** [comment]
所有从 浏览器 发出来的 https 连接都没有 密码, 无法验证, 又不能截断, 只好全部放行.

**Comment by chenxudong2020** [comment]
> 所有从 浏览器 发出来的 https 连接都没有 密码, 无法验证, 又不能截断, 只好全部放行.

一般的代理大部分都是http basic协议验证 具体的我也不清楚 但是如果插件没设置用户名和密码 浏览器会弹出http basic验证

**Comment by happytrudy** [comment]
还是一样的问题 如果这个暂时无法解决的话 回退版本吧 确实https的都是放行 http的就不行

**Comment by ssrlive** [comment]
这没法解决. 因为浏览器传过来的数据就是没有 名密 的, 无法验证. 如果因为 socks-hub 设置了密码就拦截, 这就没法用了.

**Comment by happytrudy** [comment]
> 这没法解决. 因为浏览器传过来的数据就是没有 名密 的, 无法验证. 如果因为 socks-hub 设置了密码就拦截, 这就没法用了.

没事，就这样吧 版本回退下 这个就做为内部组件使用没啥问题 要想解决这个问题就得研究下代理服务器认证流程代码改造就多了

**Comment by ssrlive** [comment]
你直接用旧版就行了. 新版不会回退的.

**Comment by ssrlive** [comment]
你看看日志输出就知道为什么修不了了.

![image](https://github.com/ssrlive/socks-hub/assets/30760636/78e6d6cb-f2f5-4da8-8f1f-debfaa3d7d0b)

**Comment by chenxudong2020** [comment]
> 你看看日志输出就知道为什么修不了了.
> 
> ![image](https://private-user-images.githubusercontent.com/30760636/308876019-78e6d6cb-f2f5-4da8-8f1f-debfaa3d7d0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMDA2MTgsIm5iZiI6MTcwOTIwMDMxOCwicGF0aCI6Ii8zMDc2MDYzNi8zMDg4NzYwMTktNzhlNmQ2Y2ItZjJmNS00ZGE4LThmMWYtZGViZmFhM2Q3ZDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA5NTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYzJiYzUzNjhjZjlkYzQxYjhkNWNkNzhkNmI4OGY4NTcyOTJlOWRmN2E3NTczMGQ0ODE0NWVhMzlmZGEyMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u2DH1phRQD6rBd3nHqK5PAKAh-AoGKvBTFUVwQ027h4)

不用改 正常的我看了下 直接从请求头https肯定获取不到
代理认证过程 https---->服务器返回407  浏览器接收到之后会弹出basic认证------------> 提交服务器返回302并回写认证头到会话----->客户端重定向并带认证头---------->正常请求 ------------>浏览器关闭 清空会话 你要是改的话代码量会有

**Comment by happytrudy** [comment]
真的不用改了 我也是大概看了下 搞这就得研究协议了

**Comment by ssrlive** [comment]
上游 SOCKS5 的密码也加上了.
