### ISSUE TITLE
A small request - working example of socks-hub (like privoxy)

### ISSUE THREAD

**Issue by SebastianMpl** [ssrlive/socks-hub#5]
Hi, 
Just found about socks-hub.
In the description I also found that it can be used as an alternative to privoxy.

Could you please provide a working example of its usage in context of blocking?

It looks to me that ACL file is something similar to hosts file:
https://github.com/NateScarlet/gfwlist.acl/blob/master/gfwlist.acl from your py script.

So should I use both listen address and socks5 address for http?
And what about HTTPS?
Is it already possible to filter HTTPS requests/response and block some web content in https?
I need to create root certificate for HTTPS. Does the application supports it somehow?

BTW: And about remote Socks5 address - i need some other app or it would also work locally?

Thank you,

**Comment by ssrlive** [comment]
The ACL file format for local machine is 
```ini
[proxy_all]

[proxy_list]
// ...

[bypass_list]
// ...
```
Here is no block option.

https://github.com/tun2proxy/socks-hub/blob/22f1ab86201f8292e882bf3e5ab9ac786e5e4b6c/src/acl/mod.rs#L279-L327

**Comment by SebastianMpl** [comment]
Thank you for your explanation.
