### ISSUE TITLE
how to convert HTTP/HTTPS proxy to SOCKS5 proxy

### ISSUE THREAD

**Issue by CarbonPool** [ssrlive/socks-hub#7]
no command argaments

**Comment by ssrlive** [comment]
```
Options:
  -t, --source-type <http|socks5>  Source proxy type [default: http] [possible values: http, socks5]
```

**Comment by CarbonPool** [comment]
> ```
> Options:
>   -t, --source-type <http|socks5>  Source proxy type [default: http] [possible values: http, socks5]
> ```

This option seems to be used to specify a new proxy protocol. I found that it automatically recognizes the forwarding protocol. Does it support http authentication forwarding to socks5?

**Comment by ssrlive** [comment]
No
> Does it support http authentication forwarding to socks5?

![image](https://github.com/user-attachments/assets/0117cec8-918d-4b1c-9430-a759e9542a24)

**Comment by CarbonPool** [comment]
> No
> 
> > Does it support http authentication forwarding to socks5?
> 
> ![image](https://private-user-images.githubusercontent.com/30760636/350897855-0117cec8-918d-4b1c-9430-a759e9542a24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjE3OTYsIm5iZiI6MTcyMTcyMTQ5NiwicGF0aCI6Ii8zMDc2MDYzNi8zNTA4OTc4NTUtMDExN2NlYzgtOTE4ZC00YjFjLTk0MzAtYTc1OWU5NTQyYTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA3NTgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMjhkMzUxYTY5ZmIxNmY4NzU1NDBhZjhlNjZjOTU0NTNlZDVkMTNkNGI1NmIwMmMzZDhmN2MyOTk0NzlmZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lp-p9X5Lm9xx72fQ7bgw17vCgsbnsmO4iuMF_SvZwgY)

thanks

**Comment by ssrlive** [comment]
now socks-hub support both http proxy and socks5 proxy on a single port.
```
socks-hub -l none://127.0.0.1:7080 -r socks5://127.0.0.1:1080 -v trace
```
